# Generated by Django 4.2.4 on 2023-12-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_calendar_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='color',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
