# Generated by Django 4.2.4 on 2023-12-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_calendar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='file',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
